### ISSUE TITLE
SoundEngine Crash

### ISSUE THREAD

**Issue by BlackAures1** [henkelmax/sound-physics-remastered#116]
**Bug description**
During the game, there was a random bug related to sound. [Gothic modpack](https://www.curseforge.com/minecraft/modpacks/play-as-dragon-gothic-edition). I'm not sure if this has anything to do with your mod at all, but if it does, here's the log and debug
[latest.log](https://github.com/henkelmax/sound-physics-remastered/files/11781280/latest.log)
[debug.log](https://github.com/henkelmax/sound-physics-remastered/files/11781281/debug.log)

```
[18Jun2023 14:04:40.667] [Render thread/ERROR] [net.minecraft.client.Minecraft/FATAL]: Unreported exception thrown!
java.util.ConcurrentModificationException: null
	at java.util.HashMap$HashIterator.remove(HashMap.java:1611) ~[?:?]
	at net.minecraft.client.sounds.SoundEngine.m_120326_(SoundEngine.java:298) ~[client-1.19.2-20220805.130853-srg.jar%23577!/:?]
	at net.minecraft.client.sounds.SoundEngine.m_120302_(SoundEngine.java:220) ~[client-1.19.2-20220805.130853-srg.jar%23577!/:?]
	at net.minecraft.client.sounds.SoundManager.m_120389_(SoundManager.java:249) ~[client-1.19.2-20220805.130853-srg.jar%23577!/:?]
	at net.minecraft.client.Minecraft.m_91398_(Minecraft.java:1801) ~[client-1.19.2-20220805.130853-srg.jar%23577!/:?]
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1078) ~[client-1.19.2-20220805.130853-srg.jar%23577!/:?]
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:700) ~[client-1.19.2-20220805.130853-srg.jar%23577!/:?]
	at net.minecraft.client.main.Main.m_239872_(Main.java:212) ~[client-1.19.2-20220805.130853-srg.jar%23577!/:?]
	at net.minecraft.client.main.Main.main(Main.java:51) ~[client-1.19.2-20220805.130853-srg.jar%23577!/:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:27) ~[fmlloader-1.19.2-43.2.14.jar%23101!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) [modlauncher-10.0.8.jar%2388!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-10.0.8.jar%2388!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-10.0.8.jar%2388!/:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-10.0.8.jar%2388!/:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-10.0.8.jar%2388!/:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-10.0.8.jar%2388!/:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-10.0.8.jar%2388!/:?]
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) [bootstraplauncher-1.1.2.jar:?]
```

**Comment by henkelmax** [comment]
You are using an outdated version. Currently only version 1.1.x are actively supported.

**Comment by BlackAures1** [comment]
On Curseforge, this is the latest version available
