### ISSUE TITLE
1.2.0 update crashes on dedicated server (1.19.2)

### ISSUE THREAD

**Issue by comp500** [henkelmax/sound-physics-remastered#134]
**Bug description**
For some reason, `SoundPhysicsConfig` tries to classload `ClientPlayerEntity`, causing a crash when run on the dedicated server.

**Steps to reproduce the issue**
1. Launch the game
2. ???
3. It crashes

**Expected behavior**
I expected it to not crash.

**Log files**
```
[11:38:26] [main/ERROR]: Failed to start the minecraft server
java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'sound_physics_remastered'!
	at org.quiltmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$2(EntrypointUtils.java:66) ~[quilt-loader-0.20.0.jar:?]
	at org.quiltmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:34) ~[quilt-loader-0.20.0.jar:?]
	at org.quiltmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:64) ~[quilt-loader-0.20.0.jar:?]
...
Caused by: java.lang.NoClassDefFoundError: net/minecraft/class_746
	at com.sonicether.soundphysics.config.SoundPhysicsConfig.reload(SoundPhysicsConfig.java:156) ~[transformed-mod-sound-physics-remastered.i0:0/:?]
	at com.sonicether.soundphysics.SoundPhysicsMod.init(SoundPhysicsMod.java:22) ~[transformed-mod-sound-physics-remastered.i0:0/:?]
	at com.sonicether.soundphysics.FabricSoundPhysicsMod.onInitialize(FabricSoundPhysicsMod.java:14) ~[transformed-mod-sound-physics-remastered.i0:0/:?]
...
Caused by: java.lang.ClassNotFoundException: net.minecraft.class_746
	at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[?:?]
	at jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188) ~[?:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:525) ~[?:?]
	at org.quiltmc.loader.impl.launch.knot.KnotClassDelegate.loadClassOnly(KnotClassDelegate.java:178) ~[quilt-loader-0.20.0.jar:?]
	at org.quiltmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:150) ~[quilt-loader-0.20.0.jar:?]
	at org.quiltmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:239) ~[quilt-loader-0.20.0.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:525) ~[?:?]
	at com.sonicether.soundphysics.config.SoundPhysicsConfig.reload(SoundPhysicsConfig.java:156) ~[transformed-mod-sound-physics-remastered.i0:0/:?]
...
```
[latest(14).log](https://github.com/henkelmax/sound-physics-remastered/files/12438804/latest.14.log) (with other mods)
[latest.log](https://github.com/henkelmax/sound-physics-remastered/files/12438822/latest.log) (no other mods)

**Versions**
- Minecraft version 1.19.2
- Quilt loader version 0.20.0
- Mod version 1.2.0

**Other mods**
Persists when no other mod is installed.

**Screenshots (Optional)**
N/A

**Comment by henkelmax** [comment]
1.20 is no longer supported.
