### ISSUE TITLE
[Log Error]Raycast too far | java.lang.Throwable: null

### ISSUE THREAD

**Issue by OcrSu** [henkelmax/sound-physics-remastered#189]
Fabric 1.20.1
Java21
Windows10

Client Log:https://mclo.gs/UeoS2Y4

This ERROR does not cause the game to crash, I just think the error log should be reported to the mod developer.

```
java.lang.Throwable: null
	at net.minecraft.class_1922.md7c0f71$imm_ptl_core$lambda$onTraverseBlocks$0$0(class_1922.java:1032) ~[client-intermediary.jar:?]
	at qouteall.q_misc_util.my_util.LimitedLogger.invoke(LimitedLogger.java:47) ~[q_misc_util-3.3.9-d99562ab8310cac6.jar:?]
	at net.minecraft.class_1922.localvar$dao000$imm_ptl_core$onTraverseBlocks(class_1922.java:1031) ~[client-intermediary.jar:?]
	at net.minecraft.class_1922.method_17744(class_1922.java) ~[client-intermediary.jar:?]
	at net.minecraft.class_1922.method_17742(class_1922.java:73) ~[client-intermediary.jar:?]
	at com.sonicether.soundphysics.SoundPhysics.raycast(SoundPhysics.java:628) ~[sound-physics-remastered-fabric-1.20.1-1.3.1.jar:?]
	at com.sonicether.soundphysics.SoundPhysics.runOcclusion(SoundPhysics.java:469) ~[sound-physics-remastered-fabric-1.20.1-1.3.1.jar:?]
	at com.sonicether.soundphysics.SoundPhysics.calculateOcclusion(SoundPhysics.java:455) ~[sound-physics-remastered-fabric-1.20.1-1.3.1.jar:?]
	at com.sonicether.soundphysics.SoundPhysics.evaluateEnvironment(SoundPhysics.java:243) ~[sound-physics-remastered-fabric-1.20.1-1.3.1.jar:?]
	at com.sonicether.soundphysics.SoundPhysics.processSound(SoundPhysics.java:181) ~[sound-physics-remastered-fabric-1.20.1-1.3.1.jar:?]
	at com.sonicether.soundphysics.SoundPhysics.onPlaySound(SoundPhysics.java:148) ~[sound-physics-remastered-fabric-1.20.1-1.3.1.jar:?]
	at net.minecraft.class_4224.handler$gog000$sound_physics_remastered$play(class_4224.java:533) ~[client-intermediary.jar:?]
	at net.minecraft.class_4224.method_19650(class_4224.java) ~[client-intermediary.jar:?]
	at net.minecraft.class_1140.method_19752(class_1140.java:461) ~[client-intermediary.jar:?]
	at net.minecraft.class_4235$class_4236.method_19737(class_4235.java:34) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_18859(class_1255.java:156) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_16075(class_1255.java:130) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_18857(class_1255.java:139) ~[client-intermediary.jar:?]
	at net.minecraft.class_4238.method_19765(class_4238.java:42) ~[client-intermediary.jar:?]
	at java.lang.Thread.run(Thread.java:1583) ~[?:?]
```

**Comment by henkelmax** [comment]
Does this happen consistently? Is this reproducible by doing something specific?

**Comment by OcrSu** [comment]
> Does this happen consistently? Is this reproducible by doing something specific?

This error occurred after I tpa'd to another player's position.
This is the first time I've seen this ERROR and the first time I've looked at the log file.
When I have time I'll test it in detail and then feed it into this issue page.

**Comment by OcrSu** [comment]
> Does this happen consistently? Is this reproducible by doing something specific?

hi.
I've found a way to reproduce the bug.
The error occurs whenever I tp to a very long distance in the same dimension.

**Comment by OcrSu** [comment]
I revisited these reported errors.
I found a name: imm_ptl_core
It's the Immersive Portal mod.

**Comment by henkelmax** [comment]
> I revisited these reported errors. I found a name: imm_ptl_core It's the Immersive Portal mod.

Oh ok, so does it also happen without immersive portals?

**Comment by OcrSu** [comment]
> > I revisited these reported errors. I found a name: imm_ptl_core It's the Immersive Portal mod.
> 
> Oh ok, so does it also happen without immersive portals?

no . it doesnt happen.

**Comment by henkelmax** [comment]
ok, can you report that to their issue tracker aswell?

**Comment by OcrSu** [comment]
> ok, can you report that to their issue tracker aswell?

its OK，I'll open an issue on the Immersive Portal mod's github in a few days.

**Comment by henkelmax** [comment]
I'm closing this due to inactivity. Feel free to reopen.

**Comment by OcrSu** [comment]
Copy that.
Was celebrating an important holiday in my country last week and I forgot about issue :)
I don't have time to keep playing with this modpack for a couple months.
Next time we are free, it will be July or August.
By then after upgrading the modpack  to the latest version, I'll leave a comment here if the issue still exists or if the problem disappears.
