### ISSUE TITLE
Create mod dont work with sound physics remastered,

### ISSUE THREAD

**Issue by RalsFemboy** [henkelmax/sound-physics-remastered#220]
### Bug description

Mod 'Create' (create) 0.5.1-f-build.1416+mc1.19.2 is incompatible with any version of mod 'Sound Physics Remastered'<br>(sound_physics_remastered), but a matching version is present: 1.19.2-1.4.2!
i rember something about steam system in create mod, i should make the icompatible thing
![image_2024-06-21_120012991](https://github.com/henkelmax/sound-physics-remastered/assets/122655584/fdf200f9-ba58-43f2-b03b-ae21125d27c1)

[11:59:10] [main/INFO]: Loading Minecraft 1.19.2 with Fabric Loader 0.15.11
[11:59:10] [ForkJoinPool-1-worker-1/WARN]: The mod "moreculling" contains invalid entries in its mod json:
- Unsupported root entry "embedded" at line 35 column 13
[11:59:12] [main/WARN]: Mod resolution failed
[11:59:12] [main/INFO]: Immediate reason: [NEG_HARD_DEP create 0.5.1-f-build.1416+mc1.19.2 {breaks sound_physics_remastered @ [*]}, ROOT_FORCELOAD_SINGLE create 0.5.1-f-build.1416+mc1.19.2, ROOT_FORCELOAD_SINGLE sound_physics_remastered 1.19.2-1.4.2]
[11:59:12] [main/INFO]: Reason: [HARD_DEP architectury 9.2.14 {depends minecraft @ [~1.20-]}, NEG_HARD_DEP create 0.5.1-f-build.1416+mc1.19.2 {breaks sound_physics_remastered @ [*]}, HARD_DEP gardens_of_the_dead 4.0.1 {depends minecraft @ [>=1.20]}, HARD_DEP terrablender 3.0.0.167 {depends minecraft @ [1.20.x]}]
[11:59:12] [main/INFO]: Fix: add [], remove [], replace [[create 0.5.1-f-build.1416+mc1.19.2] -> add:create 1 ([(-?,?)])]
[11:59:12] [main/ERROR]: Incompatible mods found!
net.fabricmc.loader.impl.FormattedException: Some of your mods are incompatible with the game or each other!
A potential solution has been determined, this may resolve your problem:
	 - Replace mod 'Create' (create) 0.5.1-f-build.1416+mc1.19.2 with any version that is compatible with:
		 - sound_physics_remastered 1.19.2-1.4.2
More details:
	 - Mod 'Architectury' (architectury) 9.2.14 requires any 1.20.x version of 'Minecraft' (minecraft), but only the wrong version is present: 1.19.2!
	 - Mod 'Create' (create) 0.5.1-f-build.1416+mc1.19.2 is incompatible with any version of mod 'Sound Physics Remastered' (sound_physics_remastered), but a matching version is present: 1.19.2-1.4.2!
	 - Mod 'Gardens of the Dead' (gardens_of_the_dead) 4.0.1 requires version 1.20 or later of 'Minecraft' (minecraft), but only the wrong version is present: 1.19.2!
	 - Mod 'TerraBlender' (terrablender) 3.0.0.167 requires any 1.20.x version of 'Minecraft' (minecraft), but only the wrong version is present: 1.19.2!
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:51) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:195) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:146) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68) [fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.15.11.jar:?]

### Minecraft version

1.19.2

### Mod version

1.19.2-1.4.2

### Mod loader and version

Fabric 0.15.11

### Steps to reproduce

Download both mods and, well....

### Log files

log in description

### Videos

i not going to record a video

**Comment by henkelmax** [comment]
See #172
