### ISSUE TITLE
crash with transit railway

### ISSUE THREAD

**Issue by lostopkk** [henkelmax/sound-physics-remastered#67]
**Bug description**
there's a block called Tactile map, it's playing a piano, when destroyed with this mod it instantly crashes

**Steps to reproduce the issue**
1. Place 'Tactile map'
2. Destroy them
3. Crash

**Log files**
for some reason it didn't save the log

**Versions**
- Minecraft version 1.19.2
- Fabric version 0.14.9 
- Mod version 1.0.12

**Comment by lostopkk** [comment]
the crash log:
[23:40:53] [Sound engine/ERROR]: Error executing task on Sound executor
java.lang.OutOfMemoryError: Java heap space
	at it.unimi.dsi.fastutil.longs.Long2ObjectOpenHashMap.rehash(Long2ObjectOpenHashMap.java:1331) ~[fastutil-8.5.6.jar:?]
	at it.unimi.dsi.fastutil.longs.Long2ObjectOpenHashMap.insert(Long2ObjectOpenHashMap.java:279) ~[fastutil-8.5.6.jar:?]
	at it.unimi.dsi.fastutil.longs.Long2ObjectOpenHashMap.put(Long2ObjectOpenHashMap.java:287) ~[fastutil-8.5.6.jar:?]
	at it.unimi.dsi.fastutil.longs.Long2ObjectFunction.put(Long2ObjectFunction.java:126) ~[fastutil-8.5.6.jar:?]
	at it.unimi.dsi.fastutil.longs.Long2ObjectMap.put(Long2ObjectMap.java:173) ~[fastutil-8.5.6.jar:?]
	at it.unimi.dsi.fastutil.longs.Long2ObjectMap.put(Long2ObjectMap.java:42) ~[fastutil-8.5.6.jar:?]
	at java.util.Map.computeIfAbsent(Map.java:1055) ~[?:?]
	at com.sonicether.soundphysics.RaycastFix.lambda$fixedRaycast$2(RaycastFix.java:49) ~[soundphysics-fabric-1.19.2-1.0.12.jar:?]
	at com.sonicether.soundphysics.RaycastFix$$Lambda$15628/0x0000000802b38cd8.apply(Unknown Source) ~[?:?]
	at com.sonicether.soundphysics.RaycastFix.traverseBlocks(RaycastFix.java:114) ~[soundphysics-fabric-1.19.2-1.0.12.jar:?]
	at com.sonicether.soundphysics.RaycastFix.fixedRaycast(RaycastFix.java:41) ~[soundphysics-fabric-1.19.2-1.0.12.jar:?]
	at com.sonicether.soundphysics.SoundPhysics.runOcclusion(SoundPhysics.java:442) ~[soundphysics-fabric-1.19.2-1.0.12.jar:?]
	at com.sonicether.soundphysics.SoundPhysics.calculateOcclusion(SoundPhysics.java:422) ~[soundphysics-fabric-1.19.2-1.0.12.jar:?]
	at com.sonicether.soundphysics.SoundPhysics.evaluateEnvironment(SoundPhysics.java:220) ~[soundphysics-fabric-1.19.2-1.0.12.jar:?]
	at com.sonicether.soundphysics.SoundPhysics.processSound(SoundPhysics.java:171) ~[soundphysics-fabric-1.19.2-1.0.12.jar:?]
	at net.minecraft.class_1140.md2979cf$lambda$tickNonPaused$0$0(class_1140.java:2135) ~[client-intermediary.jar:?]
	at net.minecraft.class_1140$$Lambda$15627/0x0000000802b388a8.accept(Unknown Source) ~[?:?]
	at net.minecraft.class_4235$class_4236.method_19737(class_4235.java:34) ~[client-intermediary.jar:?]
	at net.minecraft.class_4235$class_4236$$Lambda$11895/0x000000080260a380.run(Unknown Source) ~[?:?]
	at net.minecraft.class_1255.redirect$zln000$redirectExecuteTask(class_1255.java:521) [client-intermediary.jar:?]
	at net.minecraft.class_1255.method_16075(class_1255.java:131) [client-intermediary.jar:?]
	at net.minecraft.class_1255.method_18857(class_1255.java:140) [client-intermediary.jar:?]
	at net.minecraft.class_4238.method_19765(class_4238.java:42) [client-intermediary.jar:?]
	at net.minecraft.class_4238$$Lambda$10697/0x000000080239a9e0.run(Unknown Source) [client-intermediary.jar:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]

**Comment by henkelmax** [comment]
Please post the full logs as described in the bug template.

**Comment by henkelmax** [comment]
How much RAM did you assign to Minecraft?

**Comment by lostopkk** [comment]
> How much RAM did you assign to Minecraft?

4096 mb

**Comment by henkelmax** [comment]
Please try if it happens with more RAM assigned.

**Comment by henkelmax** [comment]
The crash you are getting is an out of memory error. This means Minecraft does not have enough RAM.

**Comment by lostopkk** [comment]
I think this is because when I break the block my minecraft is not responding, after a long time this error appears in the log, that is, it may be a memory leak

**Comment by lostopkk** [comment]
I will make a video to try to demonstrate

**Comment by henkelmax** [comment]
This exactly happens when Java runs out of memory. It tries to garbage collect unused memory, but fails to do so.
If you are making a video, please have the F3 screen open and the memory usage visible.

**Comment by lostopkk** [comment]
https://drive.google.com/file/d/10h1tlthqBR3U7pK6CgYWCUYjbNVmpOgQ/view?usp=sharing

**Comment by henkelmax** [comment]
Yeah, this seems to be caused by either Java or your system running out of memory.

**Comment by lostopkk** [comment]
I thought it was a mod error... but it's ok I think I've solved it by removing it and opening the world again, thanks for the support
